apiVersion: v1
kind: Pod
metadata:
  name: stress-testing
spec:
  containers:
    - name: stress-testing
      image: mdavidallen/neo4j-stress-testing:latest
      env:
        - name: NEO4J_URI
          value: "bolt+routing://my-internal-endpoint.default.svc.cluster.local"
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: supersecret
        - name: CONCURRENCY
          value: "10"